import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ms" | "zh" | "ta";
type Theme = "light" | "dark";
type FontSize = "small" | "medium" | "large";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.overview": "Overview",
    "nav.weather": "Weather",
    "nav.crops": "Crop Advisory",
    "nav.activeCrops": "Active Crops",
    "nav.scanner": "Crop Scanner",
    "nav.planner": "Catch-Up Planner",
    "nav.simulator": "Risk Simulator",
    "nav.market": "Market Prices",
    "nav.marketplace": "Marketplace",
    "nav.alerts": "Alerts",
    "nav.settings": "Settings",
    "nav.verification": "Verification",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    // Overview
    "overview.status": "System Status:",
    "overview.operational": "Operational",
    "overview.risks": "2 Risks Detected in Kedah District",
    "overview.activeCrops": "Active Crops",
    "overview.pendingScans": "Pending Scans",
    "overview.alerts": "Alerts",
    "overview.reports": "Reports",
    "overview.recentActivity": "Recent Activity",
    // Weather
    "weather.title": "Weather Forecast",
    "weather.temperature": "Temperature",
    "weather.rainfall": "Rainfall",
    "weather.wind": "Wind Speed",
    "weather.humidity": "Humidity",
    // Scanner
    "scanner.title": "Crop Health Scanner",
    "scanner.subtitle": "Upload seedling photos for AI analysis against golden standards",
    "scanner.upload": "Upload Seedling Photo",
    "scanner.dragDrop": "Tap or drag a photo of your seedlings (7-14 days old)",
    "scanner.gpsNote": "GPS & weather data will be captured automatically",
    "scanner.history": "Scan History",
    "scanner.generateReport": "Generate Report",
    // Planner
    "planner.title": "Catch-Up Planner",
    "planner.subtitle": "Rescue crop recommendations when original batches fail",
    "planner.seasonRemaining": "Season Remaining",
    "planner.failedBatches": "Failed Batches",
    "planner.recoveryOptions": "Recovery Options",
    "planner.available": "Available",
    "planner.limited": "Limited",
    "planner.waterNeeds": "Water Needs",
    "planner.suitability": "Suitability",
    // Simulator
    "simulator.title": "Risk Simulator",
    "simulator.subtitle": "Model crop outcomes under different weather and market scenarios",
    "simulator.selectCrops": "Select Crops to Simulate",
    "simulator.cropPreset": "Preset Crops",
    "simulator.cropCustom": "Custom Input",
    "simulator.cropPhoto": "Photo Identify",
    "simulator.cropPhotoDesc": "Take a photo to auto-identify the crop",
    "simulator.identifyingCrop": "Identifying crop...",
    "simulator.addCustomCrop": "Add",
    "simulator.cropsPlanned": "Crops Planned",
    "simulator.scenarios": "Scenario Parameters",
    "simulator.weatherChange": "Weather Scenario",
    "simulator.weatherNormal": "Normal",
    "simulator.weatherMoreRain": "More Rain (+30%)",
    "simulator.weatherDrought": "Drought (-50% rain)",
    "simulator.weatherMonsoon": "Monsoon Shift",
    "simulator.weatherFlood": "Flood Risk",
    "simulator.weatherHeatwave": "Heatwave (+5°C)",
    "simulator.weatherLaNina": "La Niña",
    "simulator.weatherElNino": "El Niño",
    "simulator.marketFluctuation": "Market Change",
    "simulator.seedQuality": "Seed Quality",
    "simulator.runSimulation": "Run Simulation",
    "simulator.reset": "Reset",
    "simulator.totalRevenue": "Total Est. Revenue",
    "simulator.avgFailureRisk": "Avg Failure Risk",
    "simulator.profitable": "Profitable",
    "simulator.moderateRiskLabel": "Moderate Risk",
    "simulator.highRiskLabel": "High Risk",
    "simulator.estYield": "Est. Yield",
    "simulator.estRevenue": "Est. Revenue",
    "simulator.failureRisk": "Failure Risk",
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account and preferences",
    "settings.profile": "Profile",
    "settings.farm": "Farm",
    "settings.notifications": "Notifications",
    "settings.display": "Display",
    "settings.regional": "Regional",
    "settings.privacy": "Privacy",
    "settings.fullName": "Full Name",
    "settings.email": "Email",
    "settings.phone": "Phone",
    "settings.role": "Role",
    "settings.farmName": "Farm Name",
    "settings.district": "District",
    "settings.state": "State",
    "settings.acreage": "Acreage (ha)",
    "settings.primaryCrop": "Primary Crop",
    "settings.secondaryCrops": "Secondary Crops",
    "settings.soilType": "Soil Type",
    "settings.alertTypes": "Alert Types",
    "settings.weatherAlerts": "Weather Alerts",
    "settings.weatherAlertsDesc": "Severe weather notifications",
    "settings.marketUpdates": "Market Updates",
    "settings.marketUpdatesDesc": "Price change notifications",
    "settings.cropAdvisory": "Crop Advisory",
    "settings.cropAdvisoryDesc": "AI-generated crop recommendations",
    "settings.seedScanResults": "Seed Scan Results",
    "settings.seedScanResultsDesc": "Scan completion notifications",
    "settings.delivery": "Delivery Method",
    "settings.emailDigest": "Email Digest",
    "settings.emailDigestDesc": "Daily summary via email",
    "settings.inAppAlerts": "In-App Notifications",
    "settings.inAppAlertsDesc": "Receive alerts within the dashboard",
    "settings.soundEffects": "Sound Effects",
    "settings.soundEffectsDesc": "In-app notification sounds",
    "settings.quietHours": "Quiet Hours",
    "settings.start": "Start",
    "settings.end": "End",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.fontSizeLabel": "Font Size",
    "settings.small": "Small",
    "settings.medium": "Medium",
    "settings.large": "Large",
    "settings.compactMode": "Compact Mode",
    "settings.compactModeDesc": "Reduce spacing and padding",
    "settings.animations": "Animations",
    "settings.animationsDesc": "Enable motion effects",
    "settings.language": "Language",
    "settings.tempUnit": "Temperature Unit",
    "settings.dateFormat": "Date Format",
    "settings.timezone": "Timezone",
    "settings.currency": "Currency",
    "settings.shareLocation": "Share Location Data",
    "settings.shareLocationDesc": "Allow GPS tracking for evidence",
    "settings.analyticsOptIn": "Analytics",
    "settings.analyticsOptInDesc": "Help improve the platform",
    "settings.publicProfile": "Public Profile",
    "settings.publicProfileDesc": "Visible to other users",
    "settings.twoFactor": "Two-Factor Auth",
    "settings.twoFactorDesc": "Extra security layer",
    "settings.dataExport": "Data Export",
    "settings.dataExportDesc": "Allow downloading your data",
    "settings.accountActions": "Account Actions",
    "settings.exportData": "Export Data",
    "settings.deleteAccount": "Delete Account",
    "settings.saved": "Settings Saved",
    "settings.savedDesc": "Your changes have been saved.",
    "settings.save": "Save Changes",
    // Pages
    "crops.title": "Crop Advisory",
    "crops.subtitle": "AI-powered crop recommendations based on weather & market data",
    "alerts.title": "Alerts & Notifications",
    "alerts.markAllRead": "Mark All Read",
    "evidence.title": "Evidence Locker",
    "evidence.subtitle": "Tamper-proof evidence reports for crop health claims",
    "market.title": "Market Prices",
    "market.subtitle": "FAMA crop price trends for Malaysian agriculture",
    // Common
    "common.refresh": "Refresh",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.noData": "No data available",
  },
  ms: {
    // Navigation
    "nav.overview": "Gambaran Keseluruhan",
    "nav.weather": "Cuaca",
    "nav.crops": "Nasihat Tanaman",
    "nav.activeCrops": "Tanaman Aktif",
    "nav.scanner": "Pengimbas Tanaman",
    "nav.planner": "Perancang Penyelamatan",
    "nav.simulator": "Simulator Risiko",
    "nav.market": "Harga Pasaran",
    "nav.marketplace": "Pasaran",
    "nav.alerts": "Amaran",
    "nav.settings": "Tetapan",
    "nav.verification": "Pengesahan",
    "nav.profile": "Profil",
    "nav.logout": "Log Keluar",
    // Overview
    "overview.status": "Status Sistem:",
    "overview.operational": "Beroperasi",
    "overview.risks": "2 Risiko Dikesan di Daerah Kedah",
    "overview.activeCrops": "Tanaman Aktif",
    "overview.pendingScans": "Imbasan Tertunda",
    "overview.alerts": "Amaran",
    "overview.reports": "Laporan",
    "overview.recentActivity": "Aktiviti Terbaru",
    // Weather
    "weather.title": "Ramalan Cuaca",
    "weather.temperature": "Suhu",
    "weather.rainfall": "Hujan",
    "weather.wind": "Kelajuan Angin",
    "weather.humidity": "Kelembapan",
    // Scanner
    "scanner.title": "Pengimbas Kesihatan Tanaman",
    "scanner.subtitle": "Muat naik foto anak benih untuk analisis AI",
    "scanner.upload": "Muat Naik Foto",
    "scanner.dragDrop": "Ketik atau seret foto anak benih anda",
    "scanner.gpsNote": "Data GPS & cuaca ditangkap secara automatik",
    "scanner.history": "Sejarah Imbasan",
    "scanner.generateReport": "Jana Laporan",
    // Planner
    "planner.title": "Perancang Penyelamatan",
    "planner.subtitle": "Cadangan tanaman penyelamat",
    "planner.seasonRemaining": "Baki Musim",
    "planner.failedBatches": "Batch Gagal",
    "planner.recoveryOptions": "Pilihan Pemulihan",
    "planner.available": "Tersedia",
    "planner.limited": "Terhad",
    "planner.waterNeeds": "Keperluan Air",
    "planner.suitability": "Kesesuaian",
    // Simulator
    "simulator.title": "Simulator Risiko",
    "simulator.subtitle": "Model hasil tanaman dalam pelbagai senario",
    "simulator.selectCrops": "Pilih Tanaman",
    "simulator.cropPreset": "Tanaman Sedia",
    "simulator.cropCustom": "Input Manual",
    "simulator.cropPhoto": "Kenal Pasti Foto",
    "simulator.cropPhotoDesc": "Ambil foto untuk mengenal pasti tanaman",
    "simulator.identifyingCrop": "Mengenal pasti...",
    "simulator.addCustomCrop": "Tambah",
    "simulator.cropsPlanned": "Tanaman Dirancang",
    "simulator.scenarios": "Parameter Senario",
    "simulator.weatherChange": "Senario Cuaca",
    "simulator.weatherNormal": "Normal",
    "simulator.weatherMoreRain": "Lebih Hujan (+30%)",
    "simulator.weatherDrought": "Kemarau (-50%)",
    "simulator.weatherMonsoon": "Perubahan Monsun",
    "simulator.weatherFlood": "Risiko Banjir",
    "simulator.weatherHeatwave": "Gelombang Panas",
    "simulator.weatherLaNina": "La Niña",
    "simulator.weatherElNino": "El Niño",
    "simulator.marketFluctuation": "Perubahan Pasaran",
    "simulator.seedQuality": "Kualiti Benih",
    "simulator.runSimulation": "Jalankan Simulasi",
    "simulator.reset": "Set Semula",
    "simulator.totalRevenue": "Jumlah Anggaran",
    "simulator.avgFailureRisk": "Risiko Purata",
    "simulator.profitable": "Menguntungkan",
    "simulator.moderateRiskLabel": "Risiko Sederhana",
    "simulator.highRiskLabel": "Risiko Tinggi",
    "simulator.estYield": "Anggaran Hasil",
    "simulator.estRevenue": "Anggaran Pendapatan",
    "simulator.failureRisk": "Risiko Kegagalan",
    // Settings
    "settings.title": "Tetapan",
    "settings.subtitle": "Urus akaun dan keutamaan anda",
    "settings.profile": "Profil",
    "settings.farm": "Ladang",
    "settings.notifications": "Pemberitahuan",
    "settings.display": "Paparan",
    "settings.regional": "Serantau",
    "settings.privacy": "Privasi",
    "settings.fullName": "Nama Penuh",
    "settings.email": "Emel",
    "settings.phone": "Telefon",
    "settings.role": "Peranan",
    "settings.farmName": "Nama Ladang",
    "settings.district": "Daerah",
    "settings.state": "Negeri",
    "settings.acreage": "Keluasan (ha)",
    "settings.primaryCrop": "Tanaman Utama",
    "settings.secondaryCrops": "Tanaman Sampingan",
    "settings.soilType": "Jenis Tanah",
    "settings.alertTypes": "Jenis Amaran",
    "settings.weatherAlerts": "Amaran Cuaca",
    "settings.weatherAlertsDesc": "Pemberitahuan cuaca teruk",
    "settings.marketUpdates": "Kemas Kini Pasaran",
    "settings.marketUpdatesDesc": "Pemberitahuan perubahan harga",
    "settings.cropAdvisory": "Nasihat Tanaman",
    "settings.cropAdvisoryDesc": "Cadangan tanaman AI",
    "settings.seedScanResults": "Keputusan Imbasan",
    "settings.seedScanResultsDesc": "Pemberitahuan imbasan siap",
    "settings.delivery": "Kaedah Penghantaran",
    "settings.emailDigest": "Ringkasan Emel",
    "settings.emailDigestDesc": "Ringkasan harian melalui emel",
    "settings.inAppAlerts": "Pemberitahuan Dalam Apl",
    "settings.inAppAlertsDesc": "Terima amaran dalam papan pemuka",
    "settings.soundEffects": "Kesan Bunyi",
    "settings.soundEffectsDesc": "Bunyi pemberitahuan dalam apl",
    "settings.quietHours": "Waktu Senyap",
    "settings.start": "Mula",
    "settings.end": "Tamat",
    "settings.theme": "Tema",
    "settings.light": "Cerah",
    "settings.dark": "Gelap",
    "settings.fontSizeLabel": "Saiz Font",
    "settings.small": "Kecil",
    "settings.medium": "Sederhana",
    "settings.large": "Besar",
    "settings.compactMode": "Mod Padat",
    "settings.compactModeDesc": "Kurangkan jarak dan padding",
    "settings.animations": "Animasi",
    "settings.animationsDesc": "Aktifkan kesan gerakan",
    "settings.language": "Bahasa",
    "settings.tempUnit": "Unit Suhu",
    "settings.dateFormat": "Format Tarikh",
    "settings.timezone": "Zon Waktu",
    "settings.currency": "Mata Wang",
    "settings.shareLocation": "Kongsi Data Lokasi",
    "settings.shareLocationDesc": "Benarkan penjejakan GPS",
    "settings.analyticsOptIn": "Analitik",
    "settings.analyticsOptInDesc": "Bantu tingkatkan platform",
    "settings.publicProfile": "Profil Awam",
    "settings.publicProfileDesc": "Boleh dilihat pengguna lain",
    "settings.twoFactor": "Pengesahan Dua Faktor",
    "settings.twoFactorDesc": "Lapisan keselamatan tambahan",
    "settings.dataExport": "Eksport Data",
    "settings.dataExportDesc": "Benarkan muat turun data anda",
    "settings.accountActions": "Tindakan Akaun",
    "settings.exportData": "Eksport Data",
    "settings.deleteAccount": "Padam Akaun",
    "settings.saved": "Disimpan",
    "settings.savedDesc": "Perubahan anda telah disimpan.",
    "settings.save": "Simpan",
    // Pages
    "crops.title": "Nasihat Tanaman",
    "crops.subtitle": "Cadangan tanaman berkuasa AI berdasarkan cuaca & pasaran",
    "alerts.title": "Amaran & Pemberitahuan",
    "alerts.markAllRead": "Tanda Semua Dibaca",
    "evidence.title": "Loker Bukti",
    "evidence.subtitle": "Laporan bukti kalis gangguan untuk tuntutan integriti benih",
    "market.title": "Harga Pasaran",
    "market.subtitle": "Trend harga tanaman FAMA untuk pertanian Malaysia",
    // Common
    "common.refresh": "Muat Semula",
    "common.loading": "Memuatkan...",
    "common.save": "Simpan",
    "common.cancel": "Batal",
    "common.delete": "Padam",
    "common.edit": "Edit",
    "common.search": "Cari",
    "common.filter": "Tapis",
    "common.noData": "Tiada data",
  },
  zh: {
    // Navigation
    "nav.overview": "概览",
    "nav.weather": "天气",
    "nav.crops": "作物咨询",
    "nav.activeCrops": "活跃作物",
    "nav.scanner": "作物扫描仪",
    "nav.planner": "补救计划",
    "nav.simulator": "风险模拟器",
    "nav.market": "市场价格",
    "nav.marketplace": "市场",
    "nav.alerts": "警报",
    "nav.settings": "设置",
    "nav.verification": "验证",
    "nav.profile": "个人资料",
    "nav.logout": "登出",
    // Overview
    "overview.status": "系统状态：",
    "overview.operational": "运行中",
    "overview.risks": "在吉打区发现2个风险",
    "overview.activeCrops": "活跃作物",
    "overview.pendingScans": "待处理扫描",
    "overview.alerts": "警报",
    "overview.reports": "报告",
    "overview.recentActivity": "最近活动",
    // Weather
    "weather.title": "天气预报",
    "weather.temperature": "温度",
    "weather.rainfall": "降雨量",
    "weather.wind": "风速",
    "weather.humidity": "湿度",
    // Scanner
    "scanner.title": "作物健康扫描仪",
    "scanner.subtitle": "上传幼苗照片进行AI分析",
    "scanner.upload": "上传幼苗照片",
    "scanner.dragDrop": "点击或拖拽幼苗照片",
    "scanner.gpsNote": "GPS和天气数据将自动捕获",
    "scanner.history": "扫描历史",
    "scanner.generateReport": "生成报告",
    // Planner
    "planner.title": "补救计划",
    "planner.subtitle": "原始批次失败时的救援作物建议",
    "planner.seasonRemaining": "剩余季节",
    "planner.failedBatches": "失败批次",
    "planner.recoveryOptions": "恢复选项",
    "planner.available": "可用",
    "planner.limited": "有限",
    "planner.waterNeeds": "用水需求",
    "planner.suitability": "适合度",
    // Simulator
    "simulator.title": "风险模拟器",
    "simulator.subtitle": "在不同天气和市场情景下模拟作物结果",
    "simulator.selectCrops": "选择模拟作物",
    "simulator.cropPreset": "预设作物",
    "simulator.cropCustom": "自定义输入",
    "simulator.cropPhoto": "照片识别",
    "simulator.cropPhotoDesc": "拍照自动识别作物",
    "simulator.identifyingCrop": "正在识别...",
    "simulator.addCustomCrop": "添加",
    "simulator.cropsPlanned": "计划作物",
    "simulator.scenarios": "场景参数",
    "simulator.weatherChange": "天气场景",
    "simulator.weatherNormal": "正常",
    "simulator.weatherMoreRain": "更多降雨(+30%)",
    "simulator.weatherDrought": "干旱(-50%)",
    "simulator.weatherMonsoon": "季风转变",
    "simulator.weatherFlood": "洪水风险",
    "simulator.weatherHeatwave": "热浪(+5°C)",
    "simulator.weatherLaNina": "拉尼娜",
    "simulator.weatherElNino": "厄尔尼诺",
    "simulator.marketFluctuation": "市场变化",
    "simulator.seedQuality": "种子质量",
    "simulator.runSimulation": "运行模拟",
    "simulator.reset": "重置",
    "simulator.totalRevenue": "预计总收入",
    "simulator.avgFailureRisk": "平均失败风险",
    "simulator.profitable": "有利可图",
    "simulator.moderateRiskLabel": "中等风险",
    "simulator.highRiskLabel": "高风险",
    "simulator.estYield": "预计产量",
    "simulator.estRevenue": "预计收入",
    "simulator.failureRisk": "失败风险",
    // Settings
    "settings.title": "设置",
    "settings.subtitle": "管理您的帐户和偏好",
    "settings.profile": "个人资料",
    "settings.farm": "农场",
    "settings.notifications": "通知",
    "settings.display": "显示",
    "settings.regional": "区域",
    "settings.privacy": "隐私",
    "settings.fullName": "全名",
    "settings.email": "电子邮件",
    "settings.phone": "电话",
    "settings.role": "角色",
    "settings.farmName": "农场名称",
    "settings.district": "地区",
    "settings.state": "州",
    "settings.acreage": "面积（公顷）",
    "settings.primaryCrop": "主要作物",
    "settings.secondaryCrops": "次要作物",
    "settings.soilType": "土壤类型",
    "settings.alertTypes": "警报类型",
    "settings.weatherAlerts": "天气警报",
    "settings.weatherAlertsDesc": "恶劣天气通知",
    "settings.marketUpdates": "市场更新",
    "settings.marketUpdatesDesc": "价格变动通知",
    "settings.cropAdvisory": "作物咨询",
    "settings.cropAdvisoryDesc": "AI生成的作物建议",
    "settings.seedScanResults": "扫描结果",
    "settings.seedScanResultsDesc": "扫描完成通知",
    "settings.delivery": "通知方式",
    "settings.emailDigest": "邮件摘要",
    "settings.emailDigestDesc": "每日邮件摘要",
    "settings.inAppAlerts": "应用内通知",
    "settings.inAppAlertsDesc": "在仪表板内接收警报",
    "settings.soundEffects": "音效",
    "settings.soundEffectsDesc": "应用内通知声音",
    "settings.quietHours": "静音时段",
    "settings.start": "开始",
    "settings.end": "结束",
    "settings.theme": "主题",
    "settings.light": "浅色",
    "settings.dark": "深色",
    "settings.fontSizeLabel": "字体大小",
    "settings.small": "小",
    "settings.medium": "中",
    "settings.large": "大",
    "settings.compactMode": "紧凑模式",
    "settings.compactModeDesc": "减少间距和填充",
    "settings.animations": "动画",
    "settings.animationsDesc": "启用动画效果",
    "settings.language": "语言",
    "settings.tempUnit": "温度单位",
    "settings.dateFormat": "日期格式",
    "settings.timezone": "时区",
    "settings.currency": "货币",
    "settings.shareLocation": "共享位置数据",
    "settings.shareLocationDesc": "允许GPS追踪",
    "settings.analyticsOptIn": "分析",
    "settings.analyticsOptInDesc": "帮助改善平台",
    "settings.publicProfile": "公开资料",
    "settings.publicProfileDesc": "对其他用户可见",
    "settings.twoFactor": "双重认证",
    "settings.twoFactorDesc": "额外安全层",
    "settings.dataExport": "数据导出",
    "settings.dataExportDesc": "允许下载您的数据",
    "settings.accountActions": "帐户操作",
    "settings.exportData": "导出数据",
    "settings.deleteAccount": "删除帐户",
    "settings.saved": "已保存",
    "settings.savedDesc": "您的更改已保存。",
    "settings.save": "保存",
    // Pages
    "crops.title": "作物咨询",
    "crops.subtitle": "基于天气和市场数据的AI作物建议",
    "alerts.title": "警报和通知",
    "alerts.markAllRead": "全部标记已读",
    "evidence.title": "证据柜",
    "evidence.subtitle": "防篡改的作物健康索赔证据报告",
    "market.title": "市场价格",
    "market.subtitle": "马来西亚农业作物价格趋势",
    // Common
    "common.refresh": "刷新",
    "common.loading": "加载中...",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.noData": "无可用数据",
  },
  ta: {
    // Navigation
    "nav.overview": "மேலோட்டம்",
    "nav.weather": "வானிலை",
    "nav.crops": "பயிர் ஆலோசனை",
    "nav.activeCrops": "செயலில் பயிர்கள்",
    "nav.scanner": "பயிர் ஸ்கேனர்",
    "nav.planner": "மீட்புத் திட்டம்",
    "nav.simulator": "இடர் உருவகப்படுத்தி",
    "nav.market": "சந்தை விலைகள்",
    "nav.marketplace": "சந்தை",
    "nav.alerts": "எச்சரிக்கைகள்",
    "nav.settings": "அமைப்புகள்",
    "nav.verification": "சரிபார்ப்பு",
    "nav.profile": "சுயவிவரம்",
    "nav.logout": "வெளியேறு",
    // Overview
    "overview.status": "அமைப்பு நிலை:",
    "overview.operational": "செயல்பாட்டில்",
    "overview.risks": "கெடா மாவட்டத்தில் 2 ஆபத்துகள் கண்டறியப்பட்டன",
    "overview.activeCrops": "செயலில் பயிர்கள்",
    "overview.pendingScans": "நிலுவையில் ஸ்கான்கள்",
    "overview.alerts": "எச்சரிக்கைகள்",
    "overview.reports": "அறிக்கைகள்",
    "overview.recentActivity": "சமீபத்திய நடவடிக்கை",
    // Weather
    "weather.title": "வானிலை முன்னறிவிப்பு",
    "weather.temperature": "வெப்பநிலை",
    "weather.rainfall": "மழைப்பொழிவு",
    "weather.wind": "காற்றின் வேகம்",
    "weather.humidity": "ஈரப்பதம்",
    // Scanner
    "scanner.title": "பயிர் ஆரோக்கிய ஸ்கேனர்",
    "scanner.subtitle": "AI பகுப்பாய்வுக்கு நாற்று புகைப்படங்களை பதிவேற்றவும்",
    "scanner.upload": "நாற்று புகைப்படம் பதிவேற்று",
    "scanner.dragDrop": "நாற்று புகைப்படத்தை தட்டவும் அல்லது இழுக்கவும்",
    "scanner.gpsNote": "GPS மற்றும் வானிலை தரவு தானாக பதிவு செய்யப்படும்",
    "scanner.history": "ஸ்கான் வரலாறு",
    "scanner.generateReport": "அறிக்கை உருவாக்கு",
    // Planner
    "planner.title": "மீட்புத் திட்டம்",
    "planner.subtitle": "அசல் தொகுதிகள் தோல்வியடையும் போது மீட்பு பயிர் பரிந்துரைகள்",
    "planner.seasonRemaining": "எஞ்சிய பருவம்",
    "planner.failedBatches": "தோல்வி தொகுதிகள்",
    "planner.recoveryOptions": "மீட்பு விருப்பங்கள்",
    "planner.available": "கிடைக்கும்",
    "planner.limited": "வரையறுக்கப்பட்டது",
    "planner.waterNeeds": "நீர் தேவை",
    "planner.suitability": "பொருத்தம்",
    // Simulator
    "simulator.title": "இடர் உருவகப்படுத்தி",
    "simulator.subtitle": "வெவ்வேறு வானிலை மற்றும் சந்தை சூழ்நிலைகளில் பயிர் விளைவுகளை மாதிரியாக்கு",
    "simulator.selectCrops": "பயிர்களை தேர்ந்தெடு",
    "simulator.cropPreset": "முன்னமைவு பயிர்கள்",
    "simulator.cropCustom": "தனிப்பயன் உள்ளீடு",
    "simulator.cropPhoto": "புகைப்பட அடையாளம்",
    "simulator.cropPhotoDesc": "பயிரை தானாக அடையாளம் காண புகைப்படம் எடுக்கவும்",
    "simulator.identifyingCrop": "அடையாளம் காணுகிறது...",
    "simulator.addCustomCrop": "சேர்",
    "simulator.cropsPlanned": "திட்டமிடப்பட்ட பயிர்கள்",
    "simulator.scenarios": "சூழ்நிலை அளவுருக்கள்",
    "simulator.weatherChange": "வானிலை சூழ்நிலை",
    "simulator.weatherNormal": "இயல்பான",
    "simulator.weatherMoreRain": "அதிக மழை (+30%)",
    "simulator.weatherDrought": "வறட்சி (-50%)",
    "simulator.weatherMonsoon": "பருவமழை மாற்றம்",
    "simulator.weatherFlood": "வெள்ள ஆபத்து",
    "simulator.weatherHeatwave": "வெப்ப அலை",
    "simulator.weatherLaNina": "லா நீனா",
    "simulator.weatherElNino": "எல் நீனோ",
    "simulator.marketFluctuation": "சந்தை மாற்றம்",
    "simulator.seedQuality": "விதை தரம்",
    "simulator.runSimulation": "உருவகப்படுத்தலை இயக்கு",
    "simulator.reset": "மீட்டமை",
    "simulator.totalRevenue": "மொத்த மதிப்பீட்டு வருவாய்",
    "simulator.avgFailureRisk": "சராசரி தோல்வி ஆபத்து",
    "simulator.profitable": "இலாபகரமான",
    "simulator.moderateRiskLabel": "மிதமான ஆபத்து",
    "simulator.highRiskLabel": "அதிக ஆபத்து",
    "simulator.estYield": "மதிப்பீட்டு விளைச்சல்",
    "simulator.estRevenue": "மதிப்பீட்டு வருவாய்",
    "simulator.failureRisk": "தோல்வி ஆபத்து",
    // Settings
    "settings.title": "அமைப்புகள்",
    "settings.subtitle": "உங்கள் கணக்கு மற்றும் விருப்பங்களை நிர்வகிக்கவும்",
    "settings.profile": "சுயவிவரம்",
    "settings.farm": "பண்ணை",
    "settings.notifications": "அறிவிப்புகள்",
    "settings.display": "காட்சி",
    "settings.regional": "பிராந்திய",
    "settings.privacy": "தனியுரிமை",
    "settings.fullName": "முழு பெயர்",
    "settings.email": "மின்னஞ்சல்",
    "settings.phone": "தொலைபேசி",
    "settings.role": "பங்கு",
    "settings.farmName": "பண்ணை பெயர்",
    "settings.district": "மாவட்டம்",
    "settings.state": "மாநிலம்",
    "settings.acreage": "பரப்பளவு (ஹெ)",
    "settings.primaryCrop": "முதன்மை பயிர்",
    "settings.secondaryCrops": "இரண்டாம் நிலை பயிர்கள்",
    "settings.soilType": "மண் வகை",
    "settings.alertTypes": "எச்சரிக்கை வகைகள்",
    "settings.weatherAlerts": "வானிலை எச்சரிக்கைகள்",
    "settings.weatherAlertsDesc": "கடுமையான வானிலை அறிவிப்புகள்",
    "settings.marketUpdates": "சந்தை புதுப்பிப்புகள்",
    "settings.marketUpdatesDesc": "விலை மாற்ற அறிவிப்புகள்",
    "settings.cropAdvisory": "பயிர் ஆலோசனை",
    "settings.cropAdvisoryDesc": "AI பயிர் பரிந்துரைகள்",
    "settings.seedScanResults": "ஸ்கான் முடிவுகள்",
    "settings.seedScanResultsDesc": "ஸ்கான் முடிவு அறிவிப்புகள்",
    "settings.delivery": "அறிவிப்பு முறை",
    "settings.emailDigest": "மின்னஞ்சல் சுருக்கம்",
    "settings.emailDigestDesc": "தினசரி மின்னஞ்சல் சுருக்கம்",
    "settings.inAppAlerts": "பயன்பாட்டு அறிவிப்புகள்",
    "settings.inAppAlertsDesc": "டாஷ்போர்டில் எச்சரிக்கைகளைப் பெறவும்",
    "settings.soundEffects": "ஒலி விளைவுகள்",
    "settings.soundEffectsDesc": "பயன்பாட்டு அறிவிப்பு ஒலிகள்",
    "settings.quietHours": "அமைதி நேரம்",
    "settings.start": "தொடக்கம்",
    "settings.end": "முடிவு",
    "settings.theme": "தீம்",
    "settings.light": "ஒளி",
    "settings.dark": "இருள்",
    "settings.fontSizeLabel": "எழுத்து அளவு",
    "settings.small": "சிறிய",
    "settings.medium": "நடுத்தர",
    "settings.large": "பெரிய",
    "settings.compactMode": "சுருக்க பயன்முறை",
    "settings.compactModeDesc": "இடைவெளி குறைக்கவும்",
    "settings.animations": "அனிமேஷன்கள்",
    "settings.animationsDesc": "இயக்க விளைவுகளை இயக்கு",
    "settings.language": "மொழி",
    "settings.tempUnit": "வெப்பநிலை அலகு",
    "settings.dateFormat": "தேதி வடிவம்",
    "settings.timezone": "நேர மண்டலம்",
    "settings.currency": "நாணயம்",
    "settings.shareLocation": "இருப்பிட தரவு பகிர்",
    "settings.shareLocationDesc": "GPS கண்காணிப்பை அனுமதி",
    "settings.analyticsOptIn": "பகுப்பாய்வு",
    "settings.analyticsOptInDesc": "தளத்தை மேம்படுத்த உதவுங்கள்",
    "settings.publicProfile": "பொது சுயவிவரம்",
    "settings.publicProfileDesc": "மற்ற பயனர்களுக்கு தெரியும்",
    "settings.twoFactor": "இரு-காரணி அங்கீகாரம்",
    "settings.twoFactorDesc": "கூடுதல் பாதுகாப்பு அடுக்கு",
    "settings.dataExport": "தரவு ஏற்றுமதி",
    "settings.dataExportDesc": "உங்கள் தரவை பதிவிறக்க அனுமதி",
    "settings.accountActions": "கணக்கு செயல்கள்",
    "settings.exportData": "தரவு ஏற்றுமதி",
    "settings.deleteAccount": "கணக்கை நீக்கு",
    "settings.saved": "சேமிக்கப்பட்டது",
    "settings.savedDesc": "உங்கள் மாற்றங்கள் சேமிக்கப்பட்டன.",
    "settings.save": "சேமி",
    // Pages
    "crops.title": "பயிர் ஆலோசனை",
    "crops.subtitle": "வானிலை மற்றும் சந்தை தரவின் அடிப்படையில் AI பயிர் பரிந்துரைகள்",
    "alerts.title": "எச்சரிக்கைகள் மற்றும் அறிவிப்புகள்",
    "alerts.markAllRead": "அனைத்தையும் படித்ததாகக் குறி",
    "evidence.title": "சான்று பெட்டி",
    "evidence.subtitle": "பயிர் ஆரோக்கிய உரிமைகோரல்களுக்கான ஆதார அறிக்கைகள்",
    "market.title": "சந்தை விலைகள்",
    "market.subtitle": "மலேசிய விவசாயத்திற்கான பயிர் விலை போக்குகள்",
    // Common
    "common.refresh": "புதுப்பி",
    "common.loading": "ஏற்றுகிறது...",
    "common.save": "சேமி",
    "common.cancel": "ரத்து",
    "common.delete": "நீக்கு",
    "common.edit": "திருத்து",
    "common.search": "தேடு",
    "common.filter": "வடிகட்டு",
    "common.noData": "தரவு இல்லை",
  },
};

interface SettingsContextType {
  theme: Theme;
  setTheme: (t: Theme) => void;
  fontSize: FontSize;
  setFontSize: (f: FontSize) => void;
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType>({
  theme: "light",
  setTheme: () => {},
  fontSize: "medium",
  setFontSize: () => {},
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("agro-theme") as Theme) || "light";
    }
    return "light";
  });
  const [fontSize, setFontSizeState] = useState<FontSize>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("agro-fontSize") as FontSize) || "medium";
    }
    return "medium";
  });
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("agro-language") as Language) || "en";
    }
    return "en";
  });

  const setTheme = (t: Theme) => {
    setThemeState(t);
    localStorage.setItem("agro-theme", t);
  };

  const setFontSize = (f: FontSize) => {
    setFontSizeState(f);
    localStorage.setItem("agro-fontSize", f);
  };

  const setLanguage = (l: Language) => {
    setLanguageState(l);
    localStorage.setItem("agro-language", l);
  };

  // Apply theme to document
  useEffect(() => {
    document.documentElement.classList.toggle("dark", theme === "dark");
  }, [theme]);

  // Apply font size to document
  useEffect(() => {
    document.documentElement.setAttribute("data-font-size", fontSize);
  }, [fontSize]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <SettingsContext.Provider value={{ theme, setTheme, fontSize, setFontSize, language, setLanguage, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export const useSettings = () => useContext(SettingsContext);
