export const MALAYSIA_STATE_DISTRICTS: Record<string, string[]> = {
  Kedah: [
    "Baling",
    "Bandar Baharu",
    "Kota Setar",
    "Kuala Muda",
    "Kubang Pasu",
    "Kulim",
    "Langkawi",
    "Padang Terap",
    "Pendang",
    "Pokok Sena",
    "Sik",
    "Yan",
  ],
  Perlis: ["Kangar", "Padang Besar", "Arau"],
  "Pulau Pinang": ["Timur Laut", "Barat Daya", "Seberang Perai Utara", "Seberang Perai Tengah", "Seberang Perai Selatan"],
  Perak: [
    "Batang Padang",
    "Hilir Perak",
    "Hulu Perak",
    "Kampar",
    "Kerian",
    "Kinta",
    "Kuala Kangsar",
    "Larut, Matang dan Selama",
    "Manjung",
    "Muallim",
    "Perak Tengah",
    "Bagan Datuk",
  ],
  Selangor: [
    "Gombak",
    "Hulu Langat",
    "Hulu Selangor",
    "Klang",
    "Kuala Langat",
    "Kuala Selangor",
    "Petaling",
    "Sabak Bernam",
    "Sepang",
  ],
  "Negeri Sembilan": ["Jelebu", "Jempol", "Kuala Pilah", "Port Dickson", "Rembau", "Seremban", "Tampin"],
  Melaka: ["Alor Gajah", "Jasin", "Melaka Tengah"],
  Johor: [
    "Batu Pahat",
    "Johor Bahru",
    "Kluang",
    "Kota Tinggi",
    "Kulai",
    "Mersing",
    "Muar",
    "Pontian",
    "Segamat",
    "Tangkak",
  ],
  Pahang: [
    "Bentong",
    "Bera",
    "Cameron Highlands",
    "Jerantut",
    "Kuantan",
    "Lipis",
    "Maran",
    "Pekan",
    "Raub",
    "Rompin",
    "Temerloh",
  ],
  Kelantan: ["Bachok", "Gua Musang", "Jeli", "Kota Bharu", "Kuala Krai", "Machang", "Pasir Mas", "Pasir Puteh", "Tanah Merah", "Tumpat"],
  Terengganu: ["Besut", "Dungun", "Hulu Terengganu", "Kemaman", "Kuala Nerus", "Kuala Terengganu", "Marang", "Setiu"],
  Sabah: [
    "Beaufort",
    "Beluran",
    "Kalabakan",
    "Keningau",
    "Kinabatangan",
    "Kota Belud",
    "Kota Kinabalu",
    "Kota Marudu",
    "Kuala Penyu",
    "Kudat",
    "Kunak",
    "Lahad Datu",
    "Nabawan",
    "Paitan",
    "Papar",
    "Penampang",
    "Pitas",
    "Putatan",
    "Ranau",
    "Sandakan",
    "Semporna",
    "Sipitang",
    "Tambunan",
    "Tawau",
    "Telupid",
    "Tenom",
    "Tongod",
    "Tuaran",
  ],
  Sarawak: [
    "Asajaya",
    "Bau",
    "Belaga",
    "Beluru",
    "Betong",
    "Bintulu",
    "Dalat",
    "Daro",
    "Julau",
    "Kabong",
    "Kanowit",
    "Kapit",
    "Kuching",
    "Lawas",
    "Limbang",
    "Lubok Antu",
    "Lundu",
    "Marudi",
    "Matu",
    "Meradong",
    "Miri",
    "Mukah",
    "Pakan",
    "Pusa",
    "Samarahan",
    "Saratok",
    "Sarikei",
    "Selangau",
    "Serian",
    "Sibu",
    "Simunjan",
    "Song",
    "Sri Aman",
    "Subis",
    "Tanjung Manis",
    "Tatau",
    "Tebedu",
    "Telang Usan",
  ],
  "Wilayah Persekutuan Kuala Lumpur": ["Kuala Lumpur"],
  "Wilayah Persekutuan Putrajaya": ["Putrajaya"],
  "Wilayah Persekutuan Labuan": ["Labuan"],
};

export const MALAYSIA_STATES = Object.keys(MALAYSIA_STATE_DISTRICTS);

export const DEFAULT_STATE = "Kedah";
export const DEFAULT_DISTRICT = "Kota Setar";

export function getDistrictsByState(state: string): string[] {
  return MALAYSIA_STATE_DISTRICTS[state] ?? [];
}

export function getDefaultDistrictForState(state: string): string {
  const districts = getDistrictsByState(state);
  return districts[0] || "";
}
